### ISSUE TITLE
Multiple sign ins

### ISSUE THREAD

**Issue by MayorChano** [DivySrivastava/leaflet#11]
Signing in with google or instagram makes a new account every time

**Comment by DivySrivastava** [comment]
Hey dude,
You should see utils/handlers/user.js
And see the difference between findOne() and checkUser().
I noticed that you change findOne() to checkUser() in your commits.

The correct one to use is findOne() in case of oauth sign-in. 
Check the website to see if there are multiple signins or not and then you'll check the difference.

**Comment by MayorChano** [comment]
So should I do db.findOne({id: user.sub}, cb) ?

**Comment by DivySrivastava** [comment]
Actually you should find by _id_ but as 
_username_

db.findOne{{username:user.username});
Works for me..

**Comment by DivySrivastava** [comment]
Just checkout the code on Github.
Under _routes/auth.js_

**Comment by MayorChano** [comment]
yes but google doesn't supply a username so it can't find it.

**Comment by DivySrivastava** [comment]
Ya ,
For now we use _user.name_ until we create something for the username.

Should work fine now.

**Comment by DivySrivastava** [comment]
Should I close the issue?

**Comment by MayorChano** [comment]
Ye sure, add it to the pull request first doe
