### ISSUE TITLE
You should consider changing the name 

### ISSUE THREAD

**Issue by rabbishuki** [DivySrivastava/leaflet#3]
There is a very popular JavaScript library called leaflet that takes care of maps.

I know that it is not the same thing, but the name will surely cause lots of confusion.

**Comment by jasonmcbride** [comment]
I agree we actually use the Leaflet mapping library at work :)

**Comment by kathan565** [comment]
I also agree on the same. Actually got this in my feed because was working on leaflet maps library from last couple of days..!!

**Comment by PranjalAgni** [comment]
I first thought a customized version of Leaflet(map library) is released

**Comment by utk-dev** [comment]
A popular templating engine called 'Jade' was forced to change their name to 'Pug' after some company claimed that they had the trademark of 'Jade'. This repo will get popular over time, so yeah.... We need a more marketable name.

**Comment by DivySrivastava** [comment]
Hey Guys,
Actually I got the "leaf logo" somehow on the internet...
And the name was just an trail to match the logo..
I agree with you guys and would like to know what name will be good for this project?
I am 15 year old and not so experienced in keeping names.
NOTE : This repo was previously known as "Pudding" but I had to change the name as I was not able to get a domain name
Thank you!

**Comment by Quest1mc** [comment]
Great work 😊 ....now a decent name ....Air? Breathe? I like breathe since it is simple and natural. Bee-social is also something that just popped into my head. Just spit balling here but welcome regardless.

**Comment by DivySrivastava** [comment]
Cool names dude,
But l would like a name which goes with the leaf logo as well...

**Comment by rabbishuki** [comment]
what about `sociaLeaf`?

**Comment by DivySrivastava** [comment]
It'll work...but I need
Something just out of the topic of Social media...
Something cute like Twitter.
I hope you get that.

**Comment by jasonmcbride** [comment]
Sprout
As in sprouting relationships or friendships etc. Then the leaf is still relevant.

**Comment by DivySrivastava** [comment]
Sprout is really nice..
We need to check if something like that already exists or not..
And then we can change the name!

**Comment by theone85ca** [comment]
Sprout is probably not a good name considering Sprout Social exists.

https://sproutsocial.com/

**Comment by MayorChano** [comment]
Maybe something like leaf-connect? I really like this repo by the way :)

**Comment by kprin** [comment]
You could go with smth more catsy but still containing the word leaf. For e.g 'Leafo'

**Comment by BamiGorengo** [comment]
Leafo will match to much results on google with other programming stuff because this is the most pupular scss compiler written in php: https://github.com/leafo/scssphp

**Comment by DivySrivastava** [comment]
Hey guys,
What about _Blossom_ or something like that?

**Comment by zahiddawod** [comment]
How about Peerleaf?

**Comment by DivySrivastava** [comment]
Hey guys,
I got a name which is not used by any another company or project.
*Spruce* - It's a plant which has pine like leaves..
And it also sounds good!

**Comment by MayorChano** [comment]
ooh that sounds good

**Comment by DivySrivastava** [comment]
So should I change the name to `spruce`? 
Anyone with a better name?

Thanks to all for actively participating in the discussion!

**Comment by Humadroid** [comment]
Spruce is great 👏👏 .. one more suggestion, not related to the name topic though but consider keeping a dark theme toggle ☺️

**Comment by jasonmcbride** [comment]
Spruce is good I'd change the logo though as a spruce tree has pine needles instead of deciduous leaves. Cheers.

**Comment by MayorChano** [comment]
[Here is an idea I had for the image](https://cdn.dancodes.online/Spruce-1.png)

**Comment by DivySrivastava** [comment]
I think the image is pretty cool for now...
Will change the name to _Spruce_ soon.

**Comment by israelvicars** [comment]
![spruce-icon-ideas](https://user-images.githubusercontent.com/1076105/56368985-7cfec100-61c6-11e9-9b75-eb02cded7f7e.png)

Since spruce is a needle tree, here's another icon direction to consider. Same base colors on left, middle. Right is a complement of the middle color (#9e7162). [Icon source](https://www.shareicon.net/ornament-christmas-plant-nature-twig-691753) offers a free license to use.

The branching arrangement of the needles and the branches could be played with as a metaphor for the branching nature of a social network. Starting with just one branch, one needle. Adding more needles to that branch. Adding more branches with more needles.

**Comment by tjskrish** [comment]
I say we should choose a longer name and not go for a smaller one. This place is for do-er. 

The Social Theory.

Event should allow people to co-ordinate for sporting / gaming / dance / practice / gym etc. Even live streaming!

Sorry, I am late to the party.

**Comment by DivySrivastava** [comment]
I agree with you @tjskrish.
But I think small names are easy to remember and long names sound to professional.

I think the name does not determine the quality of the product [Ex- Google].
We should focus on the features and not on the name.

Regards,
Divy Srivastava

**Comment by tjskrish** [comment]
@DivySrivastava sounds just about right. there are a few issues that needs to be fixed. i'll open up a few in the coming days. thanks for the quick response. appreciate it!

**Comment by MayorChano** [comment]
@israelvicars I made a pr where I put that logo into use in #13

**Comment by DivySrivastava** [comment]
Closing the issue!
Thanks to everyone for actively participating in the discussion.

Conclusion :- Name and logo has been changed for the project to _Spruce_.

Love you all!
